#!/bin/csh
#PBS -e /home/homes50/marora3/hw4/marora3.error
#PBS -o /home/homes50/marora3/hw4/marora3.output
#PBS -l walltime=50:00
#PBS -l cput=5:00  
#PBS -l nodes=1
cd $PBS_O_WORKDIR
mpiexec /home/homes50/marora3/hw4/par_ge_basic 512 1 matrix_512_1.txt 1 1 1 suffix

