#!/bin/csh
#PBS -m be
#PBS -e /home/homes50/marora3/hw3/pi_simple.error
#PBS -o /home/homes50/marora3/hw3/pi_simple.output
#PBS -N marora3
#PBS -l walltime=5:00
#PBS -l cput=5:00
mpiexec /home/homes50/marora3/hw3/pi_simple '128' >> /home/homes50/marora3/hw3/par_pi_op_simple_mohit.txt
mpiexec /home/homes50/marora3/hw3/pi_simple '1024' >> /home/homes50/marora3/hw3/par_pi_op_simple_mohit.txt
mpiexec /home/homes50/marora3/hw3/pi_simple '8192' >> /home/homes50/marora3/hw3/par_pi_op_simple_mohit.txt
mpiexec /home/homes50/marora3/hw3/pi_simple '65536' >> /home/homes50/marora3/hw3/par_pi_op_simple_mohit.txt
mpiexec /home/homes50/marora3/hw3/pi_simple '1048576' >> /home/homes50/marora3/hw3/par_pi_op_simple_mohit.txt

