#!/bin/csh
#PBS -m be
#PBS -e /home/homes50/marora3/hw3/marora3.error
#PBS -o /home/homes50/marora3/hw3/marora3.output
#PBS -N marora3
#PBS -l walltime=5:00
#PBS -l cput=5:00

mpiexec /home/homes50/marora3/hw3/marora3 '128' >> /home/homes50/marora3/hw3/par_pi_op_mohit.txt
mpiexec /home/homes50/marora3/hw3/marora3 '1024' >> /home/homes50/marora3/hw3/par_pi_op_mohit.txt
mpiexec /home/homes50/marora3/hw3/marora3 '8192' >> /home/homes50/marora3/hw3/par_pi_op_mohit.txt
mpiexec /home/homes50/marora3/hw3/marora3 '65536' >> /home/homes50/marora3/hw3/par_pi_op_mohit.txt
mpiexec /home/homes50/marora3/hw3/marora3 '1048576' >> /home/homes50/marora3/hw3/par_pi_op_mohit.txt
